apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
  labels:
    app: guestbook
    type: front-end

spec:
  template:
    metadata:
      name: guestbook-pod
      labels:
        app: guestbook
        type: front-end
    spec:
      containers:
        - name: guesbook-container
          image: kubernetes/guestbook:v2
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
      type: front-end
