apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
    type: service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    app: guestbook
    type: front-end
